version: '3'

services:
  db:
    container_name: carga-banco
    image: postgres
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=spostgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54320:5432"
  web:
    entrypoint: /entrypoint.sh
    container_name: carga-app
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  metabase:
    container_name: carga-metabase
    image: metabase/metabase
    volumes:
      - ~/metabase-data:/metabase-data
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
    postgres_database:
    metabase-data: