version: '3'

services:
  db:
    container_name: carga-banco
    image: postgres
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=spostgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    entrypoint: /entrypoint.sh
    container_name: carga-app
    build: .
    command:
      - python manage.py migrate
      - python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
    postgres_database: