# Generated by Django 2.2.15 on 2020-09-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description_short', models.CharField(max_length=500)),
                ('registration_from', models.DateTimeField()),
                ('registration_to', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('parent_entity', models.CharField(max_length=500)),
                ('published_by', models.CharField(max_length=500)),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=6)),
                ('verified_account', models.BooleanField(default=False)),
                ('use_opportunity_tab', models.BooleanField(default=False)),
            ],
        ),
    ]
