# Generated by Django 2.2.15 on 2020-09-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_budget',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
