# Generated by Django 2.2.15 on 2020-09-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0003_auto_20200907_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='ethnic_type',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='natural_from',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
