# Generated by Django 2.2.15 on 2020-09-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0004_auto_20200907_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Coletivo', 'Coletivo')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='address_other_info',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
