# Generated by Django 2.2.15 on 2020-09-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0005_auto_20200907_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='civil_status',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='studies',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
