# Generated by Django 2.2.15 on 2020-09-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0007_auto_20200907_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='fields_of_art',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
