# Generated by Django 2.2.15 on 2020-09-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0008_auto_20200907_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
