# Generated by Django 2.2.15 on 2020-09-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0011_auto_20200907_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='public_place',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
