# Generated by Django 2.2.15 on 2020-09-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0012_auto_20200907_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
