# Generated by Django 2.2.16 on 2020-09-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0013_auto_20200908_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('createTimestamp', models.DateTimeField()),
                ('updateTimestamp', models.DateTimeField()),
                ('parent', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
        ),
    ]
