# Generated by Django 2.2.16 on 2020-09-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0015_auto_20200921_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='status',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='edital',
            name='location_type',
            field=models.CharField(blank=True, choices=[('capital', 'Capital'), ('interior', 'Interior')], max_length=60, null=True),
        ),
    ]
