# Generated by Django 2.2.16 on 2020-09-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0017_auto_20200925_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='has_facebook',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='has_google_plus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='has_instagram',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='has_twitter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='has_website',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
