# Generated by Django 2.2.16 on 2020-09-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0018_auto_20200928_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='location',
        ),
        migrations.AddField(
            model_name='edital',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='edital_type',
            field=models.CharField(blank=True, choices=[('capital', 'capital'), ('interior', 'interior'), ('acessibilidade', 'acessibilidade')], default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='neighbourhood',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
